// @vitest-environment jsdom
import React, { act } from 'react'
import { createRoot } from 'react-dom/client'
import { afterEach, describe, expect, it, vi } from 'vitest'
import WebLandingPage, { LANDING_FEATURE_VIDEO_URL, LANDING_HERO_VIDEO_URL } from './WebLandingPage.jsx'
import webLandingSource from './WebLandingPage.jsx?raw'
import { WEB_BACKGROUND_URLS, WEB_LANDING_ART_URLS, WEB_LANDING_COMIC_URLS, selectedWebBackgroundUrl } from '../lib/webBackgroundAssets.js'

vi.mock('./TitleSceneCanvas.jsx', () => ({ default: ({ style }) => <div data-testid="title-scene-canvas" style={style} /> }))

function renderLanding() {
  const container = document.createElement('div')
  document.body.appendChild(container)
  const root = createRoot(container)
  act(() => root.render(<WebLandingPage />))
  return { container, unmount: () => act(() => { root.unmount(); container.remove() }) }
}

afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); document.body.innerHTML = '' })

describe('WebLandingPage', () => {
  it('shows the sticky game link only after passing the hero actions and hides it when returning', () => {
    let onVisibility
    const disconnect = vi.fn()
    const observe = vi.fn()
    vi.stubGlobal('IntersectionObserver', class {
      constructor(callback) { onVisibility = callback }
      observe = observe
      disconnect = disconnect
    })
    const view = renderLanding()
    const sticky = () => view.container.querySelector('.web-landing__mobile-sticky-cta')
    expect(sticky()).toBeNull()
    expect(observe).toHaveBeenCalledWith(view.container.querySelector('.web-landing__hero-actions'))
    act(() => onVisibility([{ isIntersecting: false, boundingClientRect: { bottom: 900 } }]))
    expect(sticky()).toBeNull()
    act(() => onVisibility([{ isIntersecting: false, boundingClientRect: { bottom: -1 } }]))
    expect(sticky()?.getAttribute('href')).toBe('/game')
    act(() => view.container.querySelector('.web-landing__media-controls button').click())
    act(() => view.container.querySelector('#comics .web-landing__comic-feature').dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true })))
    expect(sticky()).toBeNull()
    act(() => window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' })))
    expect(sticky()).not.toBeNull()
    act(() => onVisibility([{ isIntersecting: true, boundingClientRect: { bottom: 200 } }]))
    expect(sticky()).toBeNull()
    view.unmount()
    expect(disconnect).toHaveBeenCalledOnce()
  })
  it('keeps a 16:9 hero while the official homepage itself scrolls internally', () => {
    const view = renderLanding()
    const hero = view.container.querySelector('[data-testid="web-landing-stage"]')
    expect(webLandingSource).toContain('aspect-ratio:16 / 9')
    expect(hero.style.backgroundImage).toContain(selectedWebBackgroundUrl)
    expect(hero.style.backgroundSize).toBe('cover')
    expect(webLandingSource).toContain('height:100dvh')
    expect(webLandingSource).toContain('overflow-y:auto')
    expect(webLandingSource).toContain('scroll-margin-top: 76px')
    expect(webLandingSource).toContain('grid-template-rows: auto auto auto auto auto auto;')
    expect(webLandingSource).not.toContain('grid-template-rows: auto minmax(360px, 1fr)')
    expect(view.container.querySelector('#game-intro')).not.toBe(null)
    expect(view.container.querySelector('#media')).not.toBe(null)
    view.unmount()
  })

  it('uses the confirmed Korean hero copy by default, outlined Nanum Myeongjo title, and real game CTAs', () => {
    const view = renderLanding()
    const gameLinks = Array.from(view.container.querySelectorAll('a[href="/game"]'))
    const navCta = view.container.querySelector('.web-landing__nav-cta')
    const heroCta = view.container.querySelector('.web-landing__hero-actions .web-landing__cta')
    const languageSelect = view.container.querySelector('#web-landing-language')
    expect(languageSelect.value).toBe('ko')
    expect(Array.from(languageSelect.options, (option) => option.textContent)).toEqual(['한국어', 'English', '日本語', 'Tiếng Việt'])
    expect(view.container.querySelector('h1').textContent).toBe('탈출! 좀비학교')
    expect(view.container.textContent).toContain('종이 울리기 전에 탈출하자')
    expect(view.container.textContent).toContain('3분 30초 동안 몰려오는 좀비를 버티고 잠긴 탈출구를 열어라.')
    expect(view.container.textContent).toContain('4개 스테이지')
    expect(view.container.textContent).not.toContain('5개 스테이지')
    expect(gameLinks.length).toBeGreaterThanOrEqual(3)
    expect(navCta?.getAttribute('href')).toBe('/game')
    expect(heroCta?.getAttribute('href')).toBe('/game')
    expect(view.container.querySelector('.web-landing__mobile-cta')).toBeNull()
    expect(view.container.querySelector('.web-landing__nav-links a[href="/graphics-studio"]')).toBe(null)
    expect(webLandingSource).toContain("import '../assets/fonts/nanumMyeongjo.css'")
    expect(webLandingSource).toContain("font-family: 'Nanum Myeongjo', serif")
    expect(webLandingSource).toContain('-webkit-text-stroke: 2px #05070b')
    expect(webLandingSource).toContain('@media (max-width: 760px)')
    expect(webLandingSource).toContain('.web-landing__nav-cta {\n    display: none;')
    expect(webLandingSource).toContain('min-height: 44px')
    expect(webLandingSource).toContain('min-width: 44px')
    view.unmount()
  })

  it('switches every rendered homepage copy cluster and aria labels with no persistence', () => {
    const previousLang = document.documentElement.lang
    const view = renderLanding()
    const languageSelect = view.container.querySelector('#web-landing-language')
    expect(document.documentElement.lang).toBe('ko')
    act(() => {
      languageSelect.value = 'en'
      languageSelect.dispatchEvent(new Event('change', { bubbles: true }))
    })
    expect(view.container.querySelector('main').getAttribute('aria-label')).toBe('Escape! Zombie School official website')
    expect(document.documentElement.lang).toBe('en')
    expect(view.container.querySelector('.web-landing__brand').getAttribute('aria-label')).toBe('Escape! Zombie School home')
    expect(view.container.textContent).toContain('Escape before the bell rings')
    expect(view.container.textContent).toContain('Play Instantly Online')
    expect(view.container.textContent).toContain('4 stages')
    expect(view.container.textContent).toContain('School Background Preview')
    expect(view.container.textContent).not.toContain('종이 울리기 전에 탈출하자')
    expect(view.container.textContent).not.toContain('웹에서 바로 플레이')
    expect(view.container.textContent).not.toContain('학교 배경 미리보기')

    act(() => {
      languageSelect.value = 'ja'
      languageSelect.dispatchEvent(new Event('change', { bubbles: true }))
    })
    expect(view.container.textContent).toContain('チャイムが鳴る前に脱出しよう')
    expect(document.documentElement.lang).toBe('ja')
    expect(view.container.textContent).toContain('4つのステージ')
    expect(view.container.querySelector('.web-landing__media-controls').getAttribute('aria-label')).toBe('公式メディアを選択')

    act(() => {
      languageSelect.value = 'vi'
      languageSelect.dispatchEvent(new Event('change', { bubbles: true }))
    })
    expect(view.container.textContent).toContain('Thoát ra trước khi chuông reo')
    expect(document.documentElement.lang).toBe('vi')
    expect(view.container.textContent).toContain('4 màn chơi')
    expect(view.container.querySelector('.web-landing__final-cta a').textContent).toBe('Bắt đầu chơi')
    expect(webLandingSource).not.toContain('localStorage')
    expect(webLandingSource).not.toContain('sessionStorage')
    view.unmount()
    expect(document.documentElement.lang).toBe(previousLang)
  })

  it('keeps the three media panels collapsed until their single-row controls are selected', () => {
    const view = renderLanding()
    expect(LANDING_HERO_VIDEO_URL).toBe('')
    expect(LANDING_FEATURE_VIDEO_URL).toBe('')
    expect(view.container.querySelector('.web-landing__hero-video')).toBe(null)
    expect(view.container.querySelector('.web-landing__feature-video')).toBe(null)
    const controls = view.container.querySelectorAll('.web-landing__media-controls button')
    expect(controls).toHaveLength(3)
    expect(Array.from(controls, (button) => button.textContent)).toEqual(['만화 보기', '음악 듣기', '동영상 보기'])
    expect(webLandingSource).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(view.container.querySelector('#comics')).toBe(null)
    expect(view.container.querySelector('#music')).toBe(null)
    expect(view.container.querySelector('#videos')).toBe(null)
    expect(Array.from(controls, (button) => button.getAttribute('aria-pressed'))).toEqual(['false', 'false', 'false'])
    act(() => controls[2].click())
    expect(view.container.querySelector('#videos')).not.toBe(null)
    expect(view.container.querySelector('#comics')).toBe(null)
    expect(view.container.querySelector('#music')).toBe(null)
    expect(view.container.textContent).toContain('승인된 영상 URL 없음')
    expect(view.container.querySelectorAll('.web-landing__gallery-item')).toHaveLength(WEB_BACKGROUND_URLS.length)
    WEB_BACKGROUND_URLS.forEach((url) => expect(view.container.innerHTML).toContain(url))
    Object.values(WEB_LANDING_ART_URLS).forEach((url) => expect(view.container.innerHTML).toContain(url))
    expect(view.container.querySelectorAll('.web-landing__info-card img[loading="lazy"][decoding="async"]')).toHaveLength(3)
    expect(webLandingSource).toContain('web-landing__mobile-sticky-cta')
    expect(webLandingSource).toContain('position: sticky')
    expect(view.container.querySelector('#news')).not.toBe(null)
    expect(view.container.querySelector('[data-testid="title-scene-canvas"]').style.pointerEvents).toBe('none')
    expect(webLandingSource).toContain('prefers-reduced-motion:reduce')
    expect(webLandingSource).toContain('본문으로 건너뛰기')
    view.unmount()
  })

  it('renders five full-width horizontal comic episode bars that open the approved full comics', () => {
    const view = renderLanding()
    expect(view.container.querySelector('a[href="#comics"]').textContent).toContain('4컷 만화 보기')
    act(() => view.container.querySelector('.web-landing__media-controls button').click())
    expect(view.container.querySelector('#comics')).not.toBe(null)
    const comics = view.container.querySelectorAll('#comics .web-landing__comic-feature')
    expect(comics).toHaveLength(5)
    expect(view.container.textContent).toContain('출석부를 찾아라!')
    expect(view.container.querySelectorAll('#comics img')).toHaveLength(5)
    Object.values(WEB_LANDING_COMIC_URLS).forEach((url) => expect(view.container.innerHTML).toContain(url))
    comics.forEach((comic) => {
      expect(comic.tagName).toBe('A')
      expect(comic.getAttribute('target')).toBe('_blank')
      expect(comic.querySelector('.web-landing__comic-thumbnail')).not.toBe(null)
      expect(comic.querySelector('.web-landing__comic-action')?.textContent).toContain('전체 만화 보기')
    })
    act(() => comics[0].dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true })))
    expect(view.container.querySelector('[role="dialog"]')).not.toBe(null)
    expect(view.container.querySelector('[role="dialog"] img')?.getAttribute('src')).toBe(WEB_LANDING_COMIC_URLS.attendance)
    expect(view.container.querySelector('.web-landing__mobile-sticky-cta')).toBe(null)
    act(() => window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' })))
    expect(view.container.querySelector('[role="dialog"]')).toBe(null)
    expect(view.container.querySelector('.web-landing__mobile-sticky-cta')).toBe(null)
    expect(webLandingSource).toContain('grid-template-columns: minmax(180px, 0.36fr) minmax(0, 1fr)')
    expect(webLandingSource).toContain('grid-template-columns: 132px minmax(0, 1fr)')
    expect(webLandingSource).toContain('height: 136px')
    expect(webLandingSource).toContain('height: 96px')
    expect(webLandingSource).toContain('object-position: top')
    expect(webLandingSource).toContain('@media (max-width: 600px)')
    expect(webLandingSource).toContain('grid-template-columns: 96px minmax(0, 1fr)')
    expect(webLandingSource).toContain('.web-landing__comic-copy p {\n    display: none;')
    expect(webLandingSource).toContain('white-space: nowrap')
    expect(webLandingSource).toContain('#16A34A')
    view.unmount()
  })

  it('keeps all reveal sections visible by default and enables native scroll motion only when allowed', () => {
    const view = renderLanding()
    expect(view.container.querySelectorAll('[data-reveal]').length).toBeGreaterThan(6)
    expect(webLandingSource).toContain('@supports (animation-timeline: view())')
    expect(webLandingSource).toContain('animation-timeline: view()')
    expect(webLandingSource).toContain('@media (prefers-reduced-motion: no-preference)')
    expect(webLandingSource).toContain('@media (prefers-reduced-motion: reduce)')
    expect(webLandingSource).toContain('animation: none !important')
    view.unmount()
  })

  it('adds an accessible manual music player using only the existing locked title BGM source', () => {
    const view = renderLanding()
    act(() => view.container.querySelectorAll('.web-landing__media-controls button')[1].click())
    const player = view.container.querySelector('audio')
    const musicButton = view.container.querySelector('.web-landing__music-button')
    expect(view.container.querySelector('#music')).not.toBe(null)
    expect(player).not.toBe(null)
    expect(player.getAttribute('src')).toContain('title_bgm')
    expect(player.hasAttribute('controls')).toBe(false)
    expect(player.getAttribute('preload')).toBe('metadata')
    expect(player.hasAttribute('autoplay')).toBe(false)
    expect(musicButton.getAttribute('aria-pressed')).toBe('false')
    expect(musicButton.textContent).toContain('재생')
    expect(view.container.textContent).toContain('수동 재생 전용')
    expect(webLandingSource).not.toContain('localStorage')
    expect(webLandingSource).not.toContain('sessionStorage')
    expect(webLandingSource).toMatch(/\.web-landing__hero-video\s*\{\s*position: absolute;/)
    expect(webLandingSource).toMatch(/\.web-landing__hero-shell\s*\{\s*position: relative;/)
    expect(webLandingSource).not.toMatch(/\.web-landing__hero-video\s*\{[^}]*position: (fixed|sticky)/)
    view.unmount()
  })

  it('opens the matching collapsed panel from the existing comic, music, and video links', () => {
    const pause = vi.spyOn(HTMLMediaElement.prototype, 'pause').mockImplementation(() => {})
    const view = renderLanding()
    const links = view.container.querySelectorAll('.web-landing__nav-links a[href="#comics"], .web-landing__nav-links a[href="#music"], .web-landing__nav-links a[href="#videos"]')
    act(() => links[0].click())
    expect(view.container.querySelector('#comics')).not.toBe(null)
    act(() => links[1].click())
    expect(view.container.querySelector('#music')).not.toBe(null)
    expect(view.container.querySelector('#comics')).toBe(null)
    act(() => links[2].click())
    expect(view.container.querySelector('#videos')).not.toBe(null)
    expect(view.container.querySelector('#music')).toBe(null)
    expect(pause).toHaveBeenCalled()
    expect(webLandingSource).toContain("document.getElementById('media')?.scrollIntoView?.({ block: 'start' })")
    expect(webLandingSource).toContain('#media {\n  scroll-margin-top: 76px;')
    expect(webLandingSource).not.toContain('activeMediaRef.current?.scrollIntoView')
    view.unmount()
  })

  it('locks the official landing palette to white with clear blue and purple accents', () => {
    expect(webLandingSource).toContain('#2563EB')
    expect(webLandingSource).toContain('#7C3AED')
    expect(webLandingSource).toContain('#16A34A')
    expect(webLandingSource).toContain('#FFFFFF')
    expect(webLandingSource).toContain('#F6F8FF')
    expect(webLandingSource).toContain('#172033')
    expect(webLandingSource).toContain('linear-gradient(135deg, #2563EB 0%, #7C3AED 100%)')
    expect(webLandingSource).toContain('justify-content: flex-start;')
    expect(webLandingSource).not.toContain('#74bda9')
    expect(webLandingSource).not.toContain('#b9e2d6')
    expect(webLandingSource).not.toContain('#ff6a1a')
    expect(webLandingSource).not.toContain('#ff7a1a')
    expect(webLandingSource).not.toContain('#ff4b1f')
  })

})
