export const LANDING_LANGUAGES = [
  { code: 'ko', label: '한국어' },
  { code: 'en', label: 'English' },
  { code: 'ja', label: '日本語' },
  { code: 'vi', label: 'Tiếng Việt' },
]

export const LANDING_COPY = {
  ko: {
    languageLabel: '언어 선택', homeAria: '탈출! 좀비학교 공식 홈페이지', skip: '본문으로 건너뛰기', navigation: '공식 홈페이지 주요 탐색', brandHome: '탈출! 좀비학교 홈', official: '공식 홈페이지',
    intro: '게임 소개', howTo: '플레이 방법', comicNav: '4컷 만화 보기', musicNav: '음악', videoNav: '영상', news: '새소식', startGame: '게임 시작',
    eyebrow: 'KOREAN SCHOOL SURVIVAL ACTION', title: '탈출! 좀비학교', headline: '종이 울리기 전에 탈출하자', support: '3분 30초 동안 몰려오는 좀비를 버티고 잠긴 탈출구를 열어라.', mainActions: '주요 행동', playWeb: '웹에서 바로 플레이', howToLink: '플레이 방법 보기', officialNotice: '공식 안내', notice: '게임에 들어가기 전, 만화·음악·영상을 둘러보세요.', factsAria: '게임 특징', facts: ['3분 30초 생존', '4개 스테이지', '설치 없이 즉시 시작'], playMobile: '모바일에서 바로 플레이',
    gameplayLabel: 'GAMEPLAY', gameplay: [
      { title: '방과후 생존 액션', body: '교실에서 시작해 복도, 급식실까지 이어지는 방과후 생존 액션. 자동 공격과 성장 선택으로 짧고 강한 한 판을 만든다.' },
      { title: '무기와 업그레이드', body: '연필, 가방, 과학 플라스크처럼 학교 콘셉트 무기를 모아 좀비 무리를 밀어낸다.' },
      { title: '즉시 플레이', body: '설치 없이 웹에서 바로 시작하고, 모바일에서도 큰 버튼과 읽기 쉬운 정보 위계로 진입한다.' },
    ],
    survivalLabel: 'SURVIVAL ROUTE', survivalTitle: '생존 포인트', survival: ['체육복을 챙길 틈도 없이 시작되는 교실 탈출', '경험치를 모아 무기 카드를 고르고 생존 루트를 만든다', '탈출구가 열릴 때까지 몰려오는 좀비와 선생님 보스를 버틴다'],
    guideLabel: 'START GUIDE', guide: ['1. 웹에서 바로 플레이를 누른다', '2. 방향키 또는 모바일 터치로 이동한다', '3. 자동 공격과 업그레이드 선택으로 학교를 탈출한다'], guideCta: '지금 학교 탈출 시작',
    mediaLabel: 'OFFICIAL MEDIA', mediaTitle: '만화 · 음악 · 동영상', mediaControls: '공식 미디어 선택', comicButton: '만화 보기', musicButton: '음악 듣기', videoButton: '동영상 보기',
    comicsLabel: '4-CUT COMICS', comicsTitle: '연필 구조대의 학교 일지', comicsIntro: '좀비 친구들이 기절 대신 제자리로 돌아오는, 가볍고 명랑한 다섯 편의 4컷 만화입니다.', comicsList: '4컷 만화 5편 목록', episodeSuffix: '화', openComic: '전체 만화 보기', openComicAria: '전체 만화 열기', thumbnail: '썸네일', fullComic: '전체 만화', closeViewer: '만화 뷰어 닫기', close: '닫기', comicNavigation: '만화 편 이동', previous: '이전 편', next: '다음 편',
    comics: [
      { title: '출석부를 찾아라!', summary: '출석부를 찾던 좀비들, 연필 한 번에 모범생 모드!' },
      { title: '급식 줄은 한 줄로', summary: '급식 줄도 연필처럼 반듯하게! 오늘의 메뉴는 질서 한 스푼.' },
      { title: '바람아, 숙제는 이쪽!', summary: '날아간 숙제도 걱정 끝. 연필이 가리키는 곳이 제출함!' },
      { title: '체육관의 슈퍼 바운드', summary: '체육 시간도 안전 제일! 연필 지우개는 의외로 공 받기 명수.' },
      { title: '도서관의 쉿! 작전', summary: '도서관에서는 조용히. 좀비도 연필 신호엔 독서 모드!' },
    ],
    musicLabel: 'MUSIC PLAYER', musicTitle: '타이틀 테마', musicDescription: '현재 게임에서 들을 수 있는 잠긴 정본 타이틀 BGM입니다. 수동 재생 전용이며 자동으로 시작하지 않습니다.', musicPlayer: '타이틀 테마 재생기', play: '재생', pause: '일시정지', musicIdle: '수동 재생 전용 · 아직 재생하지 않음', musicPaused: '일시정지됨', musicPlaying: '타이틀 테마 재생 중', musicBlocked: '브라우저가 재생을 막았습니다. 버튼을 다시 눌러 주세요.', musicEnded: '재생이 끝났습니다',
    videoLabel: 'VIDEO', noVideo: '승인된 영상 URL 없음', videoIntro: '현재는 기존 승인 이미지로만 영상 자리를 안내합니다.', videoFuture: '공식 영상이 등록되면 이 카드에 수동 재생 플레이어가 연결됩니다.', videoActive: '승인 영상 슬롯이 활성화되었습니다.', videos: ['교실 생존 미리보기', '학교 배경 둘러보기', '탈출 루트 티저'],
    galleryLabel: 'MEDIA', galleryTitle: '학교 배경 미리보기', galleryAria: '공식 배경 이미지', galleryCta: '배경 속 학교로 입장', newsLabel: 'NEWS', newsItems: [
      ['웹에서 바로 시작', '설치 없이 게임 시작 버튼을 누르면 학교 탈출에 바로 도전할 수 있습니다.'],
      ['생존 루트 안내', '이동, 자동 공격, 업그레이드 선택으로 이어지는 기본 흐름을 안내합니다.'],
      ['미디어 아카이브', '게임 속 학교와 생존 장면을 공식 이미지로 확인할 수 있습니다.'],
    ],
    finalAria: '게임 시작 안내', finalEyebrow: '지금, 종이 울리기 전에', finalTitle: '학교 탈출을 시작하세요.', footerBrand: 'ESCAPE! ZOMBIE SCHOOL', footer: '공식 게임 홈페이지',
  },
  en: {
    languageLabel: 'Select language', homeAria: 'Escape! Zombie School official website', skip: 'Skip to content', navigation: 'Official website navigation', brandHome: 'Escape! Zombie School home', official: 'Official Website',
    intro: 'About the Game', howTo: 'How to Play', comicNav: 'Read 4-Panel Comics', musicNav: 'Music', videoNav: 'Videos', news: 'News', startGame: 'Start Game',
    eyebrow: 'KOREAN SCHOOL SURVIVAL ACTION', title: 'Escape! Zombie School', headline: 'Escape before the bell rings', support: 'Survive the zombie rush for 3 minutes 30 seconds and unlock the exit.', mainActions: 'Main actions', playWeb: 'Play Instantly Online', howToLink: 'See How to Play', officialNotice: 'Official notice', notice: 'Explore the comics, music, and videos before entering the game.', factsAria: 'Game highlights', facts: ['Survive 3 min 30 sec', '4 stages', 'Play instantly, no install'], playMobile: 'Play Now on Mobile',
    gameplayLabel: 'GAMEPLAY', gameplay: [
      { title: 'After-School Survival Action', body: 'Survive from the classroom through the halls and cafeteria. Auto-attacks and upgrade choices make every short run intense.' },
      { title: 'Weapons and Upgrades', body: 'Gather school-themed weapons like pencils, bags, and science flasks to push back the zombie horde.' },
      { title: 'Play Instantly', body: 'Start right in your browser with no installation. Clear, readable controls make it easy to jump in on mobile too.' },
    ],
    survivalLabel: 'SURVIVAL ROUTE', survivalTitle: 'Survival Highlights', survival: ['Escape the classroom before you can even grab your gym clothes', 'Collect XP, choose weapon cards, and build your survival route', 'Hold off zombies and teacher bosses until the exit opens'],
    guideLabel: 'START GUIDE', guide: ['1. Tap Play Instantly Online', '2. Move with the arrow keys or mobile touch controls', '3. Escape the school with auto-attacks and upgrade choices'], guideCta: 'Start Escaping the School',
    mediaLabel: 'OFFICIAL MEDIA', mediaTitle: 'Comics · Music · Videos', mediaControls: 'Choose official media', comicButton: 'Read Comics', musicButton: 'Listen to Music', videoButton: 'Watch Videos',
    comicsLabel: '4-PANEL COMICS', comicsTitle: 'The Pencil Rescue Squad’s School Diary', comicsIntro: 'Five lighthearted 4-panel comics where zombie friends find their way back instead of getting knocked out.', comicsList: 'List of five 4-panel comics', episodeSuffix: 'Episode', openComic: 'Read Full Comic', openComicAria: 'open full comic', thumbnail: 'thumbnail', fullComic: 'full comic', closeViewer: 'Close comic viewer', close: 'Close', comicNavigation: 'Comic episode navigation', previous: 'Previous', next: 'Next',
    comics: [
      { title: 'Find the Attendance Book!', summary: 'The zombies hunt for the roll book—one pencil brings out their model-student side!' },
      { title: 'One Line for Lunch', summary: 'As straight as a pencil! Today’s menu has a spoonful of order.' },
      { title: 'Wind, Homework Goes This Way!', summary: 'No worries about flying homework. Follow the pencil to the hand-in box!' },
      { title: 'The Gym’s Super Bounce', summary: 'Safety first in PE! A pencil eraser turns out to be great at catching balls.' },
      { title: 'Operation Shh! at the Library', summary: 'Keep it quiet in the library. Even zombies switch to reading mode at the pencil signal!' },
    ],
    musicLabel: 'MUSIC PLAYER', musicTitle: 'Title Theme', musicDescription: 'The original title theme heard in the game. Playback starts only when you press Play.', musicPlayer: 'Title theme player', play: 'Play', pause: 'Pause', musicIdle: 'Manual playback · Not playing yet', musicPaused: 'Paused', musicPlaying: 'Playing title theme', musicBlocked: 'Your browser blocked playback. Please press Play again.', musicEnded: 'Playback finished',
    videoLabel: 'VIDEO', noVideo: 'No approved video URL yet', videoIntro: 'Existing approved images are shown here until a video is available.', videoFuture: 'A manual-play video player will appear here when an official video is added.', videoActive: 'Approved video slot is active.', videos: ['Classroom Survival Preview', 'Explore the School', 'Escape Route Teaser'],
    galleryLabel: 'MEDIA', galleryTitle: 'School Background Preview', galleryAria: 'Official background images', galleryCta: 'Enter the School', newsLabel: 'NEWS', newsItems: [
      ['Play Instantly Online', 'Press Start Game to attempt your escape—no installation needed.'],
      ['Your Survival Route', 'Learn the basics: move, auto-attack, and choose upgrades.'],
      ['Media Archive', 'Explore official images of the school and survival scenes.'],
    ],
    finalAria: 'Start game invitation', finalEyebrow: 'Now, before the bell rings', finalTitle: 'Start your school escape.', footerBrand: 'ESCAPE! ZOMBIE SCHOOL', footer: 'Official Game Website',
  },
  ja: {
    languageLabel: '言語を選択', homeAria: '脱出！ゾンビ学校 公式サイト', skip: '本文へスキップ', navigation: '公式サイトのナビゲーション', brandHome: '脱出！ゾンビ学校 ホーム', official: '公式サイト',
    intro: 'ゲーム紹介', howTo: '遊び方', comicNav: '4コマ漫画を見る', musicNav: '音楽', videoNav: '動画', news: 'お知らせ', startGame: 'ゲーム開始',
    eyebrow: '韓国の学校が舞台のサバイバルアクション', title: '脱出！ゾンビ学校', headline: 'チャイムが鳴る前に脱出しよう', support: '3分30秒間ゾンビの群れをしのぎ、閉ざされた出口を開けよう。', mainActions: '主な操作', playWeb: 'ブラウザですぐ遊ぶ', howToLink: '遊び方を見る', officialNotice: '公式案内', notice: 'ゲームに入る前に漫画・音楽・動画をチェックしましょう。', factsAria: 'ゲームの特徴', facts: ['3分30秒のサバイバル', '4つのステージ', 'インストール不要ですぐ開始'], playMobile: 'スマホですぐ遊ぶ',
    gameplayLabel: 'ゲームプレイ', gameplay: [
      { title: '放課後サバイバルアクション', body: '教室から廊下、食堂へ。自動攻撃と成長の選択で、短くも熱い一戦を楽しもう。' },
      { title: '武器とアップグレード', body: '鉛筆、かばん、理科のフラスコなど学校らしい武器を集め、ゾンビの群れを押し返そう。' },
      { title: 'すぐにプレイ', body: 'インストールせずにブラウザで開始。スマホでも大きなボタンと見やすい画面ですぐに遊べます。' },
    ],
    survivalLabel: 'サバイバルルート', survivalTitle: '生き残るためのポイント', survival: ['体操服を手に取る暇もなく始まる教室からの脱出', '経験値を集めて武器カードを選び、生存ルートを作る', '出口が開くまでゾンビと先生ボスの猛攻に耐える'],
    guideLabel: 'スタートガイド', guide: ['1. 「ブラウザですぐ遊ぶ」を押す', '2. 矢印キーまたはスマホのタッチ操作で移動', '3. 自動攻撃とアップグレードで学校から脱出'], guideCta: '学校からの脱出を始める',
    mediaLabel: '公式メディア', mediaTitle: '漫画・音楽・動画', mediaControls: '公式メディアを選択', comicButton: '漫画を見る', musicButton: '音楽を聴く', videoButton: '動画を見る',
    comicsLabel: '4コマ漫画', comicsTitle: '鉛筆救助隊の学校日誌', comicsIntro: 'ゾンビの仲間たちが倒れる代わりに元の場所へ戻る、明るく楽しい5本の4コマ漫画です。', comicsList: '4コマ漫画5話の一覧', episodeSuffix: '話', openComic: '漫画を全編見る', openComicAria: '漫画の全編を開く', thumbnail: 'サムネイル', fullComic: '漫画の全編', closeViewer: '漫画ビューアーを閉じる', close: '閉じる', comicNavigation: '漫画の話を切り替える', previous: '前の話', next: '次の話',
    comics: [
      { title: '出席簿を探せ！', summary: '出席簿を探すゾンビたちが、鉛筆ひと振りで優等生モードに！' },
      { title: '給食の列は一列に', summary: '給食の列も鉛筆のようにまっすぐ！今日の献立には秩序をひとさじ。' },
      { title: '風よ、宿題はこっち！', summary: '飛んでいった宿題も心配無用。鉛筆が指す先が提出箱！' },
      { title: '体育館のスーパーバウンド', summary: '体育の時間も安全第一！鉛筆の消しゴムが意外なボールキャッチの名手。' },
      { title: '図書館の「しーっ」作戦', summary: '図書館では静かに。ゾンビも鉛筆の合図で読書モード！' },
    ],
    musicLabel: '音楽プレイヤー', musicTitle: 'タイトルテーマ', musicDescription: '現在のゲームで聴けるオリジナルのタイトルBGMです。再生ボタンを押したときだけ流れます。', musicPlayer: 'タイトルテーマ再生プレイヤー', play: '再生', pause: '一時停止', musicIdle: '手動再生のみ・まだ再生していません', musicPaused: '一時停止中', musicPlaying: 'タイトルテーマを再生中', musicBlocked: 'ブラウザが再生をブロックしました。もう一度ボタンを押してください。', musicEnded: '再生が終了しました',
    videoLabel: '動画', noVideo: '承認済みの動画URLはありません', videoIntro: '現在は承認済みの画像で動画欄をご案内しています。', videoFuture: '公式動画が登録されると、ここに手動再生プレイヤーが表示されます。', videoActive: '承認済み動画の枠が有効です。', videos: ['教室サバイバル予告', '学校の背景を見る', '脱出ルートティザー'],
    galleryLabel: 'メディア', galleryTitle: '学校の背景プレビュー', galleryAria: '公式背景画像', galleryCta: '背景の学校に入る', newsLabel: 'お知らせ', newsItems: [
      ['ブラウザですぐ開始', 'インストールせずにゲーム開始ボタンから学校脱出に挑戦できます。'],
      ['生存ルートガイド', '移動、自動攻撃、アップグレード選択の基本的な流れをご案内します。'],
      ['メディアアーカイブ', 'ゲームの学校とサバイバルの場面を公式画像で確認できます。'],
    ],
    finalAria: 'ゲーム開始の案内', finalEyebrow: 'さあ、チャイムが鳴る前に', finalTitle: '学校からの脱出を始めよう。', footerBrand: '脱出！ゾンビ学校', footer: '公式ゲームサイト',
  },
  vi: {
    languageLabel: 'Chọn ngôn ngữ', homeAria: 'Trang chính thức của Thoát khỏi Trường Zombie!', skip: 'Đến nội dung chính', navigation: 'Điều hướng trang chính thức', brandHome: 'Trang chủ Thoát khỏi Trường Zombie!', official: 'Trang chính thức',
    intro: 'Giới thiệu game', howTo: 'Cách chơi', comicNav: 'Xem truyện tranh 4 khung', musicNav: 'Âm nhạc', videoNav: 'Video', news: 'Tin mới', startGame: 'Bắt đầu chơi',
    eyebrow: 'GAME SINH TỒN TRONG TRƯỜNG HỌC HÀN QUỐC', title: 'Thoát khỏi Trường Zombie!', headline: 'Thoát ra trước khi chuông reo', support: 'Sống sót 3 phút 30 giây trước bầy zombie và mở lối thoát bị khóa.', mainActions: 'Thao tác chính', playWeb: 'Chơi ngay trên web', howToLink: 'Xem cách chơi', officialNotice: 'Thông báo chính thức', notice: 'Khám phá truyện tranh, âm nhạc và video trước khi vào game.', factsAria: 'Điểm nổi bật của game', facts: ['Sống sót 3 phút 30 giây', '4 màn chơi', 'Chơi ngay, không cần cài đặt'], playMobile: 'Chơi ngay trên điện thoại',
    gameplayLabel: 'LỐI CHƠI', gameplay: [
      { title: 'Sinh tồn sau giờ học', body: 'Hành động sinh tồn từ lớp học qua hành lang đến nhà ăn. Đòn đánh tự động và lựa chọn nâng cấp tạo nên những ván chơi ngắn mà gay cấn.' },
      { title: 'Vũ khí và nâng cấp', body: 'Thu thập vũ khí mang phong cách trường học như bút chì, cặp sách và bình thí nghiệm để đẩy lùi bầy zombie.' },
      { title: 'Chơi ngay lập tức', body: 'Bắt đầu ngay trên trình duyệt, không cần cài đặt. Nút lớn và thông tin dễ đọc giúp bạn chơi thuận tiện trên điện thoại.' },
    ],
    survivalLabel: 'HÀNH TRÌNH SINH TỒN', survivalTitle: 'Bí quyết sống sót', survival: ['Cuộc trốn thoát khỏi lớp bắt đầu khi chưa kịp lấy đồ thể dục', 'Thu thập kinh nghiệm, chọn thẻ vũ khí và tạo lộ trình sống sót', 'Chống lại zombie và trùm giáo viên cho đến khi lối thoát mở ra'],
    guideLabel: 'HƯỚNG DẪN BẮT ĐẦU', guide: ['1. Nhấn Chơi ngay trên web', '2. Di chuyển bằng phím mũi tên hoặc điều khiển cảm ứng', '3. Thoát khỏi trường bằng đòn đánh tự động và các nâng cấp'], guideCta: 'Bắt đầu thoát khỏi trường',
    mediaLabel: 'NỘI DUNG CHÍNH THỨC', mediaTitle: 'Truyện tranh · Âm nhạc · Video', mediaControls: 'Chọn nội dung chính thức', comicButton: 'Xem truyện tranh', musicButton: 'Nghe nhạc', videoButton: 'Xem video',
    comicsLabel: 'TRUYỆN TRANH 4 KHUNG', comicsTitle: 'Nhật ký trường học của Đội cứu hộ Bút Chì', comicsIntro: 'Năm truyện tranh 4 khung vui nhộn, nơi những người bạn zombie trở về chỗ cũ thay vì bị đánh gục.', comicsList: 'Danh sách 5 tập truyện tranh 4 khung', episodeSuffix: 'Tập', openComic: 'Xem toàn bộ truyện', openComicAria: 'mở toàn bộ truyện', thumbnail: 'ảnh thu nhỏ', fullComic: 'toàn bộ truyện', closeViewer: 'Đóng trình xem truyện', close: 'Đóng', comicNavigation: 'Chuyển tập truyện', previous: 'Tập trước', next: 'Tập sau',
    comics: [
      { title: 'Tìm sổ điểm danh!', summary: 'Lũ zombie tìm sổ điểm danh, nhưng một cái vung bút chì biến chúng thành học sinh gương mẫu!' },
      { title: 'Xếp một hàng lấy cơm', summary: 'Hàng lấy cơm thẳng như bút chì! Món hôm nay có thêm một thìa trật tự.' },
      { title: 'Gió ơi, bài tập ở đây!', summary: 'Bài tập bay mất ư? Đừng lo. Bút chì chỉ đúng hộp nộp bài!' },
      { title: 'Cú nảy siêu đỉnh trong nhà thể chất', summary: 'An toàn là trên hết trong giờ thể dục! Cục tẩy bút chì hóa ra bắt bóng rất giỏi.' },
      { title: 'Chiến dịch “Suỵt!” ở thư viện', summary: 'Giữ yên lặng trong thư viện. Ngay cả zombie cũng chuyển sang chế độ đọc sách theo hiệu lệnh bút chì!' },
    ],
    musicLabel: 'TRÌNH PHÁT NHẠC', musicTitle: 'Nhạc chủ đề', musicDescription: 'Nhạc chủ đề gốc đang có trong game. Nhạc chỉ phát khi bạn nhấn nút Phát.', musicPlayer: 'Trình phát nhạc chủ đề', play: 'Phát', pause: 'Tạm dừng', musicIdle: 'Chỉ phát thủ công · Chưa phát', musicPaused: 'Đã tạm dừng', musicPlaying: 'Đang phát nhạc chủ đề', musicBlocked: 'Trình duyệt đã chặn phát nhạc. Vui lòng nhấn lại nút Phát.', musicEnded: 'Đã phát xong',
    videoLabel: 'VIDEO', noVideo: 'Chưa có URL video được duyệt', videoIntro: 'Hiện chỉ hiển thị hình ảnh đã được duyệt để giới thiệu vị trí video.', videoFuture: 'Trình phát video thủ công sẽ xuất hiện ở đây khi có video chính thức.', videoActive: 'Vị trí video được duyệt đã kích hoạt.', videos: ['Xem trước sinh tồn trong lớp', 'Khám phá bối cảnh trường học', 'Giới thiệu lối thoát'],
    galleryLabel: 'HÌNH ẢNH', galleryTitle: 'Xem trước bối cảnh trường học', galleryAria: 'Hình nền chính thức', galleryCta: 'Bước vào ngôi trường', newsLabel: 'TIN MỚI', newsItems: [
      ['Chơi ngay trên web', 'Nhấn Bắt đầu chơi để thử thoát khỏi trường mà không cần cài đặt.'],
      ['Hướng dẫn sống sót', 'Tìm hiểu cách di chuyển, tấn công tự động và chọn nâng cấp.'],
      ['Kho nội dung', 'Xem hình ảnh chính thức về ngôi trường và những cảnh sinh tồn.'],
    ],
    finalAria: 'Lời mời bắt đầu game', finalEyebrow: 'Ngay bây giờ, trước khi chuông reo', finalTitle: 'Bắt đầu thoát khỏi trường.', footerBrand: 'THOÁT KHỎI TRƯỜNG ZOMBIE!', footer: 'Trang game chính thức',
  },
}
