export const PLAYER_MESH_SCALE = 0.2664

export const PLAYER_MESH_RAW_HEIGHT = 3.35
export const PLAYER_MESH_WORLD_HEIGHT = PLAYER_MESH_RAW_HEIGHT * PLAYER_MESH_SCALE

export const UNCONSCIOUS_STUDENT_RAW_LENGTH = 2.43
export const UNCONSCIOUS_STUDENT_PLAYER_SCALE = Number(
  (PLAYER_MESH_WORLD_HEIGHT / UNCONSCIOUS_STUDENT_RAW_LENGTH).toFixed(4)
)
