import { UNCONSCIOUS_STUDENT_PLAYER_SCALE } from '../../lib/characterVisualScale.js'

export const STAGE_OBJECT_PLACEMENTS = {
  stage1: [
    {
      id: 'stage1-desk-nw-01',
      type: 'classroomDesk',
      position: [-15.6, 0, -15.8],
      rotation: [0, 0.42, 0],
      scale: 0.832,
      props: { variant: 'upright' },
    },
    {
      id: 'stage1-chair-nw-01',
      type: 'classroomChair',
      position: [-13.4, 0, -13.2],
      rotation: [0, -0.92, 0],
      scale: 0.736,
      props: { variant: 'tilted' },
    },
    {
      id: 'stage1-desk-ne-01',
      type: 'classroomDesk',
      position: [15.8, 0, -15.2],
      rotation: [0, -0.72, 0],
      scale: 0.784,
      props: { variant: 'abandoned' },
    },
    {
      id: 'stage1-chair-ne-01',
      type: 'classroomChair',
      position: [13.2, 0, -13.6],
      rotation: [0, 1.28, 0],
      scale: 0.704,
      props: { variant: 'overturned' },
    },
    {
      id: 'stage1-desk-sw-01',
      type: 'classroomDesk',
      position: [-15.8, 0, 14.6],
      rotation: [0, 1.35, 0],
      scale: 0.816,
      props: { variant: 'overturned' },
    },
    {
      id: 'stage1-student-sw-01',
      type: 'unconsciousStudent',
      position: [-13.2, 0, 15.8],
      rotation: [0, -0.68, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'faceUp' },
    },
    {
      id: 'stage1-student-sw-02',
      type: 'unconsciousStudent',
      position: [-17.1, 0, 11.8],
      rotation: [0, 2.16, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'sideRight' },
    },
    {
      id: 'stage1-student-south-01',
      type: 'unconsciousStudent',
      position: [-7.4, 0, 17.2],
      rotation: [0, 1.42, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'sideLeft' },
    },
    {
      id: 'stage1-desk-se-01',
      type: 'classroomDesk',
      position: [15.6, 0, 15.4],
      rotation: [0, -1.18, 0],
      scale: 0.8,
      props: { variant: 'abandoned' },
    },
    {
      id: 'stage1-student-se-01',
      type: 'unconsciousStudent',
      position: [13.4, 0, 14.2],
      rotation: [0, 0.86, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'sideLeft' },
    },
    {
      id: 'stage1-student-se-02',
      type: 'unconsciousStudent',
      position: [17.2, 0, 10.8],
      rotation: [0, -2.28, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'faceUp' },
    },
    {
      id: 'stage1-student-south-02',
      type: 'unconsciousStudent',
      position: [6.6, 0, 17.0],
      rotation: [0, -1.68, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'sideRight' },
    },
    {
      id: 'stage1-desk-west-02',
      type: 'classroomDesk',
      position: [-17.4, 0, -4.2],
      rotation: [0, 2.55, 0],
      scale: 0.768,
      props: { variant: 'tilted' },
    },
    {
      id: 'stage1-chair-west-02',
      type: 'classroomChair',
      position: [-16.2, 0, 4.8],
      rotation: [0, -2.8, 0],
      scale: 0.688,
      props: { variant: 'abandoned' },
    },
    {
      id: 'stage1-student-west-01',
      type: 'unconsciousStudent',
      position: [-18.2, 0, 0.6],
      rotation: [0, -2.02, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'faceUp' },
    },
    {
      id: 'stage1-student-nw-01',
      type: 'unconsciousStudent',
      position: [-17.0, 0, -10.4],
      rotation: [0, 0.52, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'sideLeft' },
    },
    {
      id: 'stage1-desk-east-02',
      type: 'classroomDesk',
      position: [17.4, 0, 4.4],
      rotation: [0, -2.35, 0],
      scale: 0.752,
      props: { variant: 'abandoned' },
    },
    {
      id: 'stage1-chair-east-02',
      type: 'classroomChair',
      position: [16.1, 0, -4.8],
      rotation: [0, 2.7, 0],
      scale: 0.672,
      props: { variant: 'tilted' },
    },
    {
      id: 'stage1-student-east-01',
      type: 'unconsciousStudent',
      position: [18.0, 0, -0.4],
      rotation: [0, 1.94, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'sideRight' },
    },
    {
      id: 'stage1-student-ne-01',
      type: 'unconsciousStudent',
      position: [16.8, 0, -10.2],
      rotation: [0, -0.48, 0],
      scale: UNCONSCIOUS_STUDENT_PLAYER_SCALE,
      props: { variant: 'faceUp' },
    },
  ],
  stage2: [
    {
      id: 'stage2-desk-left-top',
      type: 'classroomDesk',
      position: [-10.4, 0, -22],
      rotation: [0, Math.PI / 2, 0],
      scale: 0.768,
    },
    {
      id: 'stage2-desk-right-mid',
      type: 'classroomDesk',
      position: [10.3, 0, -8],
      rotation: [0, -Math.PI / 2, 0],
      scale: 0.752,
    },
    {
      id: 'stage2-desk-left-low',
      type: 'classroomDesk',
      position: [-10.1, 0, 10],
      rotation: [0, Math.PI / 2 - 0.08, 0],
      scale: 0.784,
    },
    {
      id: 'stage2-desk-right-bottom',
      type: 'classroomDesk',
      position: [10.2, 0, 24],
      rotation: [0, -Math.PI / 2 + 0.06, 0],
      scale: 0.8,
    },
  ],
}

export function getStageObjectPlacements(stageId = 'stage1') {
  return STAGE_OBJECT_PLACEMENTS[stageId] ?? []
}
