[CmdletBinding(SupportsShouldProcess=$true,ConfirmImpact='Medium')]
param()
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$name='EscapeZombieSchool-FacebookPosting';$path='\';$times=@('11:00','17:00')
$description='EscapeZombieSchool Facebook visible-UI posting: 11:00,17:00 Asia/Seoul; interactive desktop required.'
$tz=Get-TimeZone;if($tz.Id -notin @('Korea Standard Time','Asia/Seoul')){throw "Host timezone '$($tz.Id)' is not KST"}
$runner=(Resolve-Path (Join-Path $PSScriptRoot 'Invoke-FacebookScheduledPosting.ps1')).ProviderPath;$ps=(Resolve-Path (Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe')).ProviderPath;$sid=[Security.Principal.WindowsIdentity]::GetCurrent().User.Value;$taskArguments='-NoProfile -STA -WindowStyle Hidden -ExecutionPolicy Bypass -File "{0}"' -f $runner
$old=@(Get-ScheduledTask -TaskPath $path|Where-Object{$_.TaskName -ceq $name});if($old.Count -and $old[0].Description -cne $description){throw 'Existing task ownership differs'}
if(-not $PSCmdlet.ShouldProcess($path+$name,'Register 11:00 and 17:00 KST Facebook task')){[pscustomobject]@{status='planned';times=$times;logonType='InteractiveToken';postingStarted=$false}|ConvertTo-Json;return}
$action=New-ScheduledTaskAction -Execute $ps -Argument $taskArguments -WorkingDirectory $PSScriptRoot;$triggers=@($times|ForEach-Object{New-ScheduledTaskTrigger -Daily -At ([datetime]::Today.Add([TimeSpan]::Parse($_)))})
$principal=New-ScheduledTaskPrincipal -UserId $sid -LogonType Interactive -RunLevel Limited;$settings=New-ScheduledTaskSettingsSet -MultipleInstances IgnoreNew -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries;$settings.StartWhenAvailable=$false;$settings.RestartCount=0;$settings.Enabled=$true
Register-ScheduledTask -TaskName $name -TaskPath $path -Action $action -Trigger $triggers -Principal $principal -Settings $settings -Description $description -Force|Out-Null
try{$task=Get-ScheduledTask -TaskName $name -TaskPath $path;[xml]$xml=Export-ScheduledTask -TaskName $name -TaskPath $path;$ns=[Xml.XmlNamespaceManager]::new($xml.NameTable);$ns.AddNamespace('t',$xml.DocumentElement.NamespaceURI);$nodes=@($xml.SelectNodes('/t:Task/t:Triggers/t:CalendarTrigger',$ns));$saved=@($nodes|ForEach-Object{if($_.SelectSingleNode('t:ScheduleByDay/t:DaysInterval',$ns).InnerText -ne '1' -or $null -ne $_.SelectSingleNode('t:Repetition',$ns) -or ($_.SelectSingleNode('t:Enabled',$ns) -and $_.SelectSingleNode('t:Enabled',$ns).InnerText -ne 'true')){throw 'Trigger is not enabled daily non-repeating'};([datetime]::Parse($_.SelectSingleNode('t:StartBoundary',$ns).InnerText)).ToString('HH:mm')}|Sort-Object);$logon=$xml.SelectSingleNode('/t:Task/t:Principals/t:Principal/t:LogonType',$ns);$user=$xml.SelectSingleNode('/t:Task/t:Principals/t:Principal/t:UserId',$ns);$multi=$xml.SelectSingleNode('/t:Task/t:Settings/t:MultipleInstancesPolicy',$ns);$startWhenAvailable=[bool]$task.Settings.StartWhenAvailable;$restartCount=[int]$task.Settings.RestartCount;if($task.State -ne 'Ready' -or $nodes.Count -ne 2 -or ($saved-join ',') -cne ($times-join ',') -or $logon.InnerText -ne 'InteractiveToken' -or $user.InnerText -ne $sid -or $multi.InnerText -ne 'IgnoreNew' -or $startWhenAvailable -or $restartCount -ne 0 -or @($task.Actions).Count -ne 1 -or $task.Actions[0].Execute -cne $ps -or $task.Actions[0].Arguments -cne $taskArguments -or $task.Actions[0].WorkingDirectory -cne $PSScriptRoot){throw 'Task readback differs'};[pscustomobject]@{status='registered_verified';times=$saved;postingStarted=$false}|ConvertTo-Json}
catch{Disable-ScheduledTask -TaskName $name -TaskPath $path|Out-Null;throw "Readback failed; task disabled: $($_.Exception.Message)"}
